// One maintained entry per component; runtime dependencies are found from its source closure.
import motionReferences from "./motion-references.json" with { type: "json" }
export const components = [
  ["button", "UiButton", "core"], ["field", "UiField", "core"],
  ["textarea", "UiTextarea", "core"], ["select", "UiSelect", "core"],
  ["checkbox", "UiCheckboxField", "core"], ["status-badge", "UiStatusBadge", "core"],
  ["notice", "UiNotice", "core"], ["progress", "UiProgress", "core"], ["skeleton", "UiSkeleton", "core"],
  ["agent-status", "AgentStatus", "agent"], ["tool-call", "ToolCallCard", "agent"],
  ["approval", "ToolApprovalPanel", "agent"], ["agent-message", "AgentMessage", "agent"],
  ["agent-timeline", "AgentTimeline", "agent"], ["agent-composer", "AgentPromptComposer", "agent"],
  ["workspace-header", "WorkspaceHeader", "workspace"], ["list-toolbar", "ListToolbar", "workspace"],
  ["workspace-stat", "WorkspaceStatCard", "workspace"], ["workspace-empty", "WorkspaceEmptyState", "workspace"],
  ["workspace-pagination", "WorkspacePagination", "workspace"], ["dialog", "UiDialog", "core"],
  ["alert-dialog", "UiAlertDialog", "core"], ["dropdown-menu", "UiDropdownMenu", "core"], ["popover", "UiPopover", "core"],
  ["tooltip", "UiTooltip", "core"], ["tabs", "UiTabs", "core"], ["switch", "UiSwitch", "core"],
  ["radio-group", "UiRadioGroup", "core"], ["toast", "UiToastHost", "core"],
  ["form-group", "UiFormGroup", "core"], ["combobox", "UiCombobox", "core"], ["multi-select", "UiMultiSelect", "core"],
  ["date-range-picker", "UiDateRangePicker", "core"],
  ["file-upload", "UiFileUpload", "core"],
  ["filter-bar", "UiFilterBar", "workspace"],
  ["data-table", "UiDataTable", "workspace"],
  ["batch-action-bar", "UiBatchActionBar", "workspace"],
  ["settings-section", "UiSettingsSection", "workspace"], ["sidebar-nav", "UiSidebarNav", "workspace"],
  ["thinking-indicator", "UiThinkingIndicator", "motion"], ["streaming-text", "UiStreamingText", "motion"],
  ["reasoning-panel", "UiReasoningPanel", "motion"], ["animated-number", "UiAnimatedNumber", "motion"],
  ["shimmer-text", "UiShimmerText", "motion"], ["border-beam", "UiBorderBeam", "motion"],
  ["spotlight-card", "UiSpotlightCard", "motion"], ["animated-list", "UiAnimatedList", "motion"],
  ["shine-button", "UiShineButton", "motion"], ["ripple-button", "UiRippleButton", "motion"],
  ["gradient-text", "UiGradientText", "motion"], ["rotating-text", "UiRotatingText", "motion"],
  ["blur-reveal", "UiBlurReveal", "motion"], ["tilt-card", "UiTiltCard", "motion"],
  ["marquee", "UiMarquee", "motion"], ["compare-slider", "UiCompareSlider", "motion"],
  ["dock", "UiDock", "motion"], ["meteor-card", "UiMeteorCard", "motion"],
  ["accordion", "UiAccordion", "core"], ["breadcrumb", "UiBreadcrumb", "core"],
  ["avatar-group", "UiAvatarGroup", "core"], ["carousel", "UiCarousel", "core"],
  ["circular-progress", "UiCircularProgress", "core"],
  ["command-menu", "UiCommandMenu", "workspace"], ["step-navigation", "UiStepNavigation", "workspace"],
  ["terminal", "UiTerminal", "workspace"], ["file-tree", "UiFileTree", "workspace"],
  ["split-pane", "UiSplitPane", "workspace"],
  ["orbit-display", "UiOrbitDisplay", "motion"], ["text-highlight", "UiTextHighlight", "motion"],
].map(([id, title, group]) => ({ id, title, group, reference: motionReferences[id], source: `registry/ui/own-ui-${id}.tsx`, example: `registry/ui/examples/${id}-example.tsx` }))

export const groups = [
  { id: "core", title: "Own UI Core", source: "registry/ui/own-ui-core.tsx" },
  { id: "agent-ui", title: "Own UI Agent", source: "registry/ui/own-ui-agent.tsx" },
  { id: "workspace-ui", title: "Own UI Workspace", source: "registry/ui/own-ui-workspace.tsx" },
]
