import type { ComponentEntry } from "./catalog"
import references from "../registry/motion-references.json"

const entries = [
  { id: "meteor-card", name: "流星背景", english: "UiMeteorCard", description: "轻量光线从卡片背景划过，内容与操作保持清楚。", fit: "灵感、功能或重点内容卡片；固定8道装饰光线。", variants: "children、active；标准 HTML 属性与主题颜色。", states: "播放、暂停、收藏演示；系统减少动态时隐藏光线。", accessibility: "背景 aria-hidden 且不挡点击；操作保留原生语义。" },
  { id: "tilt-card", name: "倾斜卡片", english: "UiTiltCard", description: "跟随指针轻微倾斜，离开时回正；键盘聚焦有静态高亮。", fit: "组件、功能与作品展示；内部可放真实按钮。", variants: "children、active；原生 pointer 回调保留；旋转限制在正负6度。", states: "指针移动、离开、停用、键盘聚焦；触摸保持静态。", accessibility: "不新增 Tab 焦点；支持减少动态；子内容语义不变。" },
  { id: "gradient-text", name: "渐变文字", english: "UiGradientText", description: "绿色与蓝色沿文字流动，突出展示标题或重点内容。", fit: "标题与强调文字；字号与语义元素由调用者提供。", variants: "children、active；颜色来自主题变量。", states: "播放、暂停；减少动态时显示纯色文本。", accessibility: "保留可读文本，颜色不表示业务状态。" },
  { id: "compare-slider", name: "前后对比", english: "UiCompareSlider", description: "拖动原生滑块，在两份静态内容之间移动分界线。", fit: "界面、图片和效果前后对比；视觉插槽仅用于静态内容。", variants: "before/after、label、beforeLabel/afterLabel、value/onValueChange、disabled；value限定0—100，无效值回退50。", states: "拖动、方向键/Home/End、禁用、恢复中间；示例不加载外部图片。", accessibility: "原生 range 与 label、明确百分比；视觉层 inert/aria-hidden，不隐藏可操作内容。" },
  { id: "dock", name: "悬浮 Dock", english: "UiDock", description: "图标入口在悬浮与聚焦时放大，旁边入口轻微响应。", fit: "少量常用入口；路由与权限由项目控制。", variants: "稳定唯一 items.id、label、icon、disabled；受控 value/onSelect。", states: "悬浮、Tab/Enter/空格、当前项、禁用项、空列表。", accessibility: "命名 nav、带名称的原生按钮、aria-current；减少动态时不放大。" },
  { id: "marquee", name: "无缝滚动", english: "UiMarquee", description: "展示项连续流动，悬浮或聚焦时暂停，停用后全部静态展示。", fit: "标识、标签和短展示卡片；主列表的语义保留。", variants: "稳定唯一 items.id/content、label、active；固定22秒循环。", states: "连续滚动、悬浮/聚焦暂停、静态；减少动态时自动换行显示全部项目。", accessibility: "原始 ul 可读，重复层 aria-hidden/inert；不让复制层重复进入键盘顺序。" },
  { id: "shine-button", name: "流光按钮", english: "UiShineButton", description: "一束细光扫过按钮，沿用现有按钮的尺寸、层级和业务回调。", fit: "突出主要操作；按场景少量使用。", variants: "UiButton 的 variant、size、busy、disabled、原生属性与 ref。", states: "流光、点击、键盘、禁用/处理中；减少动态时无光束。", accessibility: "原生 button；禁用阻止操作；装饰不改变按钮名称。" },
  { id: "ripple-button", name: "点击涟漪", english: "UiRippleButton", description: "点击位置产生扩散波纹，键盘激活从中心响应。", fit: "明确的按钮点击反馈；调用方提供真实动作。", variants: "UiButton 的 variant、size、busy、disabled、原生属性与 ref。", states: "鼠标、触摸、Enter/空格、连续点击、禁用；单个涟漪400ms后移除。", accessibility: "装饰 aria-hidden；减少动态时不创建涟漪；保留原生提交与回调。" },
  { id: "rotating-text", name: "轮换文字", english: "UiRotatingText", description: "文字切换时向上入场，定时播放由示例或项目控制。", fit: "短标题中的关键词切换；组件本身没有定时器。", variants: "text；标准 span 属性；每次更新播放300ms入场。", states: "自动轮换、暂停、手动下一词；示例跟随减少动态偏好停止自动播放。", accessibility: "只渲染当前文本，不自动实时播报；示例可暂停且列出全部词语。" },
  { id: "blur-reveal", name: "模糊入场", english: "UiBlurReveal", description: "内容从模糊与轻微偏移中显现，隐藏时保留布局位置。", fit: "受控内容入场和隐藏；不包含滚动监听或布局折叠。", variants: "children、visible；标准 div 属性；300ms过渡。", states: "显示、隐藏、反复切换；减少动态时立即切换。", accessibility: "隐藏内容 inert 且 aria-hidden，内部按钮退出 Tab 顺序。" },
  { id: "thinking-indicator", name: "思考状态", english: "UiThinkingIndicator", description: "轨道微光、呼吸图标与思考文案，完成后切换为静态反馈。", fit: "Agent 工作状态、生成进度；实际状态和文案由项目提供。", variants: "active、label、description；标准 HTML 属性。", states: "思考中、已完成；示例可切换。", accessibility: "role=status；装饰图标隐藏；系统减少动态时静止。" },
  { id: "streaming-text", name: "流式文本", english: "UiStreamingText", description: "新文字逐字从模糊中显现，搭配生成光标。", fit: "展示逐步接收到的文本；网络、Markdown 和模型调用由项目提供。", variants: "text、streaming；纯文本输出，不执行 HTML。", states: "生成中、暂停、完成、重新生成；本地定时器仅在示例中。", accessibility: "视觉文字 aria-hidden，生成阶段只播报状态，完成后播报全文；支持减少动态。" },
  { id: "reasoning-panel", name: "推理展开", english: "UiReasoningPanel", description: "平滑展开处理摘要，步骤按顺序入场并显示进行状态。", fit: "用户可见的处理摘要与工具执行步骤。", variants: "title、steps、open/onOpenChange；受控展开。", states: "展开、收起、待处理、进行中、完成、失败。", accessibility: "原生按钮、aria-expanded/controls；收起内容 inert 且 aria-hidden；状态有文字。" },
  { id: "animated-number", name: "滚动数字", english: "UiAnimatedNumber", description: "指标数值平滑增长或减少，连续更新时从当前值继续。", fit: "统计值与结果数量；金额计算留在业务层。", variants: "value、decimals（0—6）、duration（0—2000ms）；默认650ms。", states: "计数、重复更新、归零；无效数字回退为0，支持减少动态。", accessibility: "辅助技术读取目标值，视觉帧不逐次播报；卸载取消动画。" },
  { id: "shimmer-text", name: "流光文字", english: "UiShimmerText", description: "一道细微光线扫过重点文字，支持播放与暂停。", fit: "生成提示、展示标题或重点说明。", variants: "children、active；字体与字号由调用方指定。", states: "播放、暂停、静态；减少动态时显示普通文字。", accessibility: "保留可读文本语义，不用闪烁隐藏文字。" },
  { id: "border-beam", name: "边框光束", english: "UiBorderBeam", description: "光束沿卡片边缘流动，让重点内容有可见的动态层次。", fit: "处理中的卡片、展示区块；卡片内容自行组合。", variants: "children、active；语义主色、警告色和卡片圆角变量。", states: "播放、暂停；减少动态时保持静态边框。", accessibility: "光束是 CSS 装饰，业务状态需要另行提供文字。" },
  { id: "spotlight-card", name: "聚光卡片", english: "UiSpotlightCard", description: "柔和光斑跟随指针，键盘聚焦时也突出当前卡片。", fit: "组件入口、功能卡片与作品展示。", variants: "children、原生 pointer 回调、className 和 style。", states: "指针移动、离开复原、键盘聚焦；触摸不追光。", accessibility: "不额外抢占 Tab 焦点；子内容保留语义；减少动态时关闭追光。" },
  { id: "animated-list", name: "动态列表", english: "UiAnimatedList", description: "通知和任务依次淡入，新增内容自然进入当前列表。", fit: "任务动态、通知流和执行记录；数据顺序由项目控制。", variants: "items 的稳定 id/content、label；每项间隔40ms，上限400ms。", states: "初始入场、追加、清空；示例保留最近3条。", accessibility: "原生 ul/li 与命名列表；示例提供更新摘要；减少动态时取消入场。" },
] as const

export const motionEntries: ComponentEntry[] = entries.map(entry => ({ ...entry, group: "motion", tags: ["动效", references[entry.id].name], reference: references[entry.id], dependencies: "React；CSS Module；无需额外动画依赖。", importPath: `@/components/ui/own-ui-${entry.id}` }))
