import type { ComponentEntry } from "./catalog"
import references from "../registry/motion-references.json"

const entries = [
  { id: "command-menu", group: "workspace", name: "命令菜单", english: "UiCommandMenu", description: "搜索与键盘选择常用操作，在对话框里直接执行。", fit: "小型命令集合；真实操作、权限与全局快捷键由项目提供。", variants: "受控 open/onOpenChange；稳定唯一 items.id、label、description、disabled；onSelect。", states: "搜索、无匹配、方向键循环、Enter 选择、全禁用、Esc 关闭、重新打开清空搜索。", accessibility: "命名对话框、搜索 combobox 与 listbox、活动项关联；输入法组字期间不执行命令；关闭恢复焦点。", dependencies: "React；@base-ui/react@1.8.0；UiDialog / UiField。" },
  { id: "accordion", group: "core", name: "折叠面板", english: "UiAccordion", description: "一次展开一份内容，面板高度平滑变化。", fit: "FAQ、设置补充与分组说明；有限数量的面板。", variants: "items.id/title/content/disabled；受控 value（string 或 null）/onValueChange。", states: "展开、收起、禁用；250ms 高度过渡；减少动态时立即切换。", accessibility: "Base UI 管理按钮、标题与面板关联；Tab、Enter、空格操作；不依赖箭头键导航。", dependencies: "React；@base-ui/react@1.8.0；局部 CSS Module。" },
  { id: "carousel", group: "core", name: "轮播", english: "UiCarousel", description: "手动翻页的内容轮播，滑动切换保持明确边界。", fit: "少量内容卡片与产品介绍；不自动播放，不接管全局方向键。", variants: "items.id/title/content；受控数值 value/onValueChange、label；索引截断并限制到有效范围，无效值回退 0。", states: "首尾按钮禁用、翻页、内部操作、空数据；350ms 过渡。", accessibility: "命名 region、幻灯片与页码；非当前页 aria-hidden/inert；减少动态时直接切换。", dependencies: "React；UiButton；局部 CSS Module。" },
  { id: "file-tree", group: "workspace", name: "文件树", english: "UiFileTree", description: "展开嵌套文件夹，选择当前文件并保留层级。", fit: "有限层级的文件导航；只显示调用者传入的数据，不访问文件系统。", variants: "有限无循环 nodes：稳定唯一 id、name、children、disabled；受控 value/onSelect、label。", states: "原生 details 展开/收起、选择/清除、禁用文件或文件夹、空数据。", accessibility: "命名 nav 与嵌套 ul；summary 使用原生键盘行为；文件为按钮；未实现 ARIA tree 的箭头导航。", dependencies: "React；UiButton；局部 CSS Module。" },
  { id: "split-pane", group: "workspace", name: "可调分栏", english: "UiSplitPane", description: "用滑块调整左右内容的空间比例。", fit: "双栏内容、预览与侧边信息；通过下方滑块调整。", variants: "first/second 内容插槽；受控 value/onValueChange、label、disabled；25—75，无效值回退 50。", states: "拖动滑块、方向键/Home/End、禁用、均分；长文字自动换行。", accessibility: "原生 range、关联 label 和左右百分比说明；两个内容插槽始终可操作。", dependencies: "React；局部 CSS Module。" },
  { id: "step-navigation", group: "workspace", name: "步骤导航", english: "UiStepNavigation", description: "展示当前步骤，让短流程可以逐步或直接切换。", fit: "设置向导与短流程；完成判断、校验和跳转限制由项目负责。", variants: "稳定唯一 steps.id/label/disabled；受控 value/onValueChange、label。", states: "当前步骤、直接选择、前后切换、禁用；窄容器换行。", accessibility: "命名 nav、有序列表与按钮；aria-current=step 标记当前位置。", dependencies: "React；UiButton；局部 CSS Module。" },
  { id: "avatar-group", group: "core", name: "头像组", english: "UiAvatarGroup", description: "重叠排列成员头像，缺少图片时显示名字首字。", fit: "协作成员与参与者；全部传入成员保留名称。", variants: "稳定唯一 items.id、name、可选 src；label；图片加载失败显示首个 Unicode 字符。", states: "图片、首字回退、图片失败、追加/收起成员、空列表；窄容器换行。", accessibility: "命名 ul 与有名称的成员；装饰图片空 alt，首字 aria-hidden；不是可交互入口。", dependencies: "React；局部 CSS Module。" },
  { id: "breadcrumb", group: "core", name: "面包屑", english: "UiBreadcrumb", description: "显示页面的层级路径，长路径自然换行。", fit: "项目、收藏与文档路径；真实 href 由项目提供。", variants: "稳定唯一 items.id/label、可选 href；label；最后一项显示为当前页。", states: "多级/单级/空路径、长文字、原生链接跳转；不处理路由状态。", accessibility: "命名 nav、ol、原生链接；最后一项 aria-current=page；分隔符隐藏。", dependencies: "React；局部 CSS Module；可用于服务端静态渲染。" },
  { id: "terminal", group: "workspace", name: "终端日志", english: "UiTerminal", description: "以清楚的终端样式展示纯文本日志，支持复制。", fit: "执行日志与任务反馈；不执行命令，不解析 ANSI 或 HTML。", variants: "title；稳定唯一 lines.id/text；tone=neutral/success/error；日志正文由项目提供。", states: "追加、清空、内部滚动、复制成功/失败；空日志禁用复制。", accessibility: "命名 role=log、温和播报新增内容；复制结果有状态文本；减少动态时无入场动画。", dependencies: "React；UiButton；浏览器 Clipboard API（安全上下文与权限）。" },
  { id: "orbit-display", group: "motion", name: "轨道展示", english: "UiOrbitDisplay", description: "能力图标围绕中心缓慢运行，暂停时保持当前位置。", fit: "静态能力或集成展示；2—8 项环绕，其他数量静态排列全部项目。", variants: "稳定唯一 items.id/label/icon；center、label、active；固定 24 秒循环。", states: "播放、暂停、悬浮暂停、静态排列；减少动态时停转。", accessibility: "命名列表与项目名称；图标装饰隐藏；插槽用于静态展示。", dependencies: "React；局部 CSS Module；无需动画依赖。" },
  { id: "circular-progress", group: "core", name: "环形进度", english: "UiCircularProgress", description: "环形轨迹展示确定进度，未知进度时缓慢旋转。", fit: "任务与准备进度；真实数值由项目提供。", variants: "value、label；有限数值限制 0—100；缺省/NaN/Infinity 视为未知进度。", states: "0%、中间、完成、数值更新、未知进度；减少动态时静止。", accessibility: "role=progressbar、名称与范围；未知进度省略 aria-valuenow；SVG 装饰隐藏。", dependencies: "React；局部 CSS Module；可用于服务端静态渲染。" },
  { id: "text-highlight", group: "motion", name: "文字划线", english: "UiTextHighlight", description: "柔和的划线标记从左侧展开，突出短句中的重点。", fit: "短行文字强调；字号和上层语义由项目决定。", variants: "children、active；标准 mark 属性；350ms 单次划线。", states: "显示、隐藏、重播；减少动态时静态标记。", accessibility: "原生 mark 语义，文字始终可读；动画不触发实时播报。", dependencies: "React；局部 CSS Module；无需动画依赖。" },
] as const

export const patternEntries: ComponentEntry[] = entries.map(entry => {
  const reference = references[entry.id as keyof typeof references]
  return { ...entry, tags: [entry.group === "motion" ? "动效" : "组合组件", ...(reference ? [reference.name] : [])], reference, importPath: `@/components/ui/own-ui-${entry.id}` }
})
